#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: lint-shell

on:
  pull_request:
    paths:
      - "**/*.sh"
  workflow_dispatch:

jobs:
  shellcheck:
    name: lint-shell
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: "."
          pattern: "*.sh"
          exclude: |
            ./.git/*
            ./**/node_modules/*
          check_all_files_with_shebangs: false
          fail_on_error: true
          level: warning
          shellcheck_flags: "--external-sources"
