name: Metrics
on:
  schedule:
    - cron: "0 20 */2 * *"
  workflow_dispatch:

permissions:
  id-token: write
  actions: read
  contents: write
  pull-requests: read
  security-events: read

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, notable, notable_repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: no
          plugin_repositories: yes
          plugin_achievements: yes
          plugin_notable: yes
          # plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_lines: yes
          plugin_topics: yes
          # plugin_topics_limit: 0
          plugin_topics_mode: icons
          # plugin_followup: yes
          # plugin_followup_indepth: yes
          # plugin_stargazers: yes
          config_order: base.header, isocalendar, languages, repositories, achievements, notable, notable_repositories
          filename: metrics.base.svg
